// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjD270X38Hfmx6NPcLM61AzG6bzXs4_Vw',
    appId: '1:426606618920:web:ef7f4e7a3e4a8b04fb881d',
    messagingSenderId: '426606618920',
    projectId: 'bc-scanner-6c45a',
    authDomain: 'bc-scanner-6c45a.firebaseapp.com',
    databaseURL: 'https://bc-scanner-6c45a.firebaseio.com',
    storageBucket: 'bc-scanner-6c45a.firebasestorage.app',
    measurementId: 'G-TMT8VDZRVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0HOrLjPnQq1sz7Db8n7dKcyeE4P-d_o',
    appId: '1:426606618920:android:43e276fc0f9364b6fb881d',
    messagingSenderId: '426606618920',
    projectId: 'bc-scanner-6c45a',
    databaseURL: 'https://bc-scanner-6c45a.firebaseio.com',
    storageBucket: 'bc-scanner-6c45a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRLiWVG7SuX_ey72A8Zt0f2VzUE2jqB-8',
    appId: '1:426606618920:ios:d97ded23c2ced199fb881d',
    messagingSenderId: '426606618920',
    projectId: 'bc-scanner-6c45a',
    databaseURL: 'https://bc-scanner-6c45a.firebaseio.com',
    storageBucket: 'bc-scanner-6c45a.firebasestorage.app',
    iosBundleId: 'com.example.nervousSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjD270X38Hfmx6NPcLM61AzG6bzXs4_Vw',
    appId: '1:426606618920:web:a74b90a314a45031fb881d',
    messagingSenderId: '426606618920',
    projectId: 'bc-scanner-6c45a',
    authDomain: 'bc-scanner-6c45a.firebaseapp.com',
    databaseURL: 'https://bc-scanner-6c45a.firebaseio.com',
    storageBucket: 'bc-scanner-6c45a.firebasestorage.app',
    measurementId: 'G-26QWJXY9FJ',
  );

}